instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: jenkins-master
    properties:
      jenkins:
        admin:
          email: buildtools@finkit.com
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
        server:
          address: ((jenkins_server_url))
    release: jenkins
  name: jenkins-master
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_extensions:
  - internet-required
  - jenkins-pool
  vm_type: default
- azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: jenkins-slave
    properties:
      jenkins:
        slave:
          executors: 2
          labels: build
          master_password: ((jenkins_agent_password))
          master_username: agent
          mode: exclusive
    release: jenkins
  name: jenkins-slave
  networks:
  - name: default
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    properties:
      nexus:
        admin:
          password: ((nexus_admin_password))
        deployer:
          password: ((nexus_deployer_password))
        developer:
          password: ((nexus_developer_password))
    release: nexus
  name: nexus
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  - nexus-pool
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: sonarqube
    properties:
      sonar:
        admin:
          password: ((sonar_admin_password))
    release: sonarqube
  name: sonarqube
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  - sonar-pool
  vm_type: default
name: buildstack
os: ubuntu-trusty
releases:
- name: newrelic-infra-bosh
  sha1: 5be785540118f1b3fab909ba30f64b30e48f76a5
  url: https://github.com/dazjones/newrelic-infra-bosh/releases/download/v0.1.2/newrelic-infra-bosh-0.1.2.tgz
  version: 0.1.2
- name: stackdriver-tools
  sha1: 9785cd55b7b15df43ffe890ab66b398634e6e841
  url: https://github.com/cloudfoundry-community/stackdriver-tools/releases/download/v2.0.1/stackdriver-tools-2.0.1.tgz
  version: 2.0.1
- name: jenkins
  sha1: 1705f6a88a370213cb2562d7dcddfebc927ace14
  url: https://storage.googleapis.com/dev-build-automate-release-tarballs/jenkins-boshrelease/jenkins-boshrelease-v0.0.27.tgz
  version: 0.0.27
- name: nexus
  sha1: 1658e6f386ad8543c6440aa3b99afff7de47908e
  url: https://storage.googleapis.com/dev-build-automate-release-tarballs/nexus-boshrelease/nexus-boshrelease-v1.0.10.tgz
  version: 1.0.10
- name: sonarqube
  sha1: ed172010738d54459351156f5617f3a393bd56e3
  url: https://storage.googleapis.com/dev-build-automate-release-tarballs/sonarqube-boshrelease/sonarqube-boshrelease-v0.0.22.tgz
  version: 0.0.22
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3586.16"
update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000
variables:
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
- name: nexus_admin_password
  type: password
- name: nexus_deployer_password
  type: password
- name: nexus_developer_password
  type: password
- name: sonar_admin_password
  type: password
- name: sonar_mysql_password
  type: password

